services:
  devops-service:
    image: "nguyenvanhai2005/devops-service:latest"
    container_name: devops-service
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "devops-service"
    deploy:
      resources:
        limits:
          memory: 700m